/**
 * Blog del male 1.0.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Author { 
    id?: string;
    username?: string;
    email?: string;
    name?: string;
    avatar?: string;
    created?: Date;
    updated?: Date;
}