/**
 * Blog del male 1.0.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Tweet } from '../model/tweet';
import { TweetsPagenated } from '../model/tweetsPagenated';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TweetService {

    protected basePath = 'http://localhost:8090/api/collections';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param tweetId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createTweet(body: Tweet, tweetId: string, observe?: 'body', reportProgress?: boolean): Observable<Tweet>;
    public createTweet(body: Tweet, tweetId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Tweet>>;
    public createTweet(body: Tweet, tweetId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Tweet>>;
    public createTweet(body: Tweet, tweetId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createTweet.');
        }

        if (tweetId === null || tweetId === undefined) {
            throw new Error('Required parameter tweetId was null or undefined when calling createTweet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Tweet>('post',`${this.basePath}/tweets/records/${encodeURIComponent(String(tweetId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param tweetId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteTweet(tweetId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteTweet(tweetId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteTweet(tweetId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteTweet(tweetId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (tweetId === null || tweetId === undefined) {
            throw new Error('Required parameter tweetId was null or undefined when calling deleteTweet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/tweets/records/${encodeURIComponent(String(tweetId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param page 
     * @param perPage 
     * @param sort 
     * @param filter 
     * @param expand 
     * @param fields 
     * @param skipTotal 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllTweets(page?: number, perPage?: number, sort?: string, filter?: string, expand?: string, fields?: string, skipTotal?: boolean, observe?: 'body', reportProgress?: boolean): Observable<TweetsPagenated>;
    public getAllTweets(page?: number, perPage?: number, sort?: string, filter?: string, expand?: string, fields?: string, skipTotal?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TweetsPagenated>>;
    public getAllTweets(page?: number, perPage?: number, sort?: string, filter?: string, expand?: string, fields?: string, skipTotal?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TweetsPagenated>>;
    public getAllTweets(page?: number, perPage?: number, sort?: string, filter?: string, expand?: string, fields?: string, skipTotal?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {








        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (perPage !== undefined && perPage !== null) {
            queryParameters = queryParameters.set('perPage', <any>perPage);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('filter', <any>filter);
        }
        if (expand !== undefined && expand !== null) {
            queryParameters = queryParameters.set('expand', <any>expand);
        }
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields', <any>fields);
        }
        if (skipTotal !== undefined && skipTotal !== null) {
            queryParameters = queryParameters.set('skipTotal', <any>skipTotal);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<TweetsPagenated>('get',`${this.basePath}/tweets/records`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param tweetId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateTweet(body: Tweet, tweetId: string, observe?: 'body', reportProgress?: boolean): Observable<Tweet>;
    public updateTweet(body: Tweet, tweetId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Tweet>>;
    public updateTweet(body: Tweet, tweetId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Tweet>>;
    public updateTweet(body: Tweet, tweetId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateTweet.');
        }

        if (tweetId === null || tweetId === undefined) {
            throw new Error('Required parameter tweetId was null or undefined when calling updateTweet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Tweet>('put',`${this.basePath}/tweets/records/${encodeURIComponent(String(tweetId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
